import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import Sidebar from "@/components/SideBar";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Providers from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <Sidebar variant="sidebar" collapsible="icon" />
            <main className="flex flex-col">
              <SidebarTrigger />
              <section className="p-4">{children}</section>
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
